Repository brilliantshell/ft_transcendence, pull requests merged in 2022-12, with the labels that each got.

#15 :hammer: chore : Dev Containers 로 개발 환경 구축하기
  backend/.commit_template
  backend/.devcontainer/devcontainer.json
  backend/.env.sample
  backend/Dockerfile
  backend/Dockerfile.dev
  backend/file
  backend/package-lock.json
  backend/package.json
  backend/test.js
  database/.commit_template
  database/.devcontainer/devcontainer.json
  database/.env.sample
  database/Dockerfile
  database/Dockerfile.dev
  database/postgresql.conf
  docker-compose.dev.yml
  docker-compose.yml
  frontend/.commit_template
  frontend/.devcontainer/devcontainer.json
  frontend/.env.sample
  frontend/Dockerfile
  frontend/Dockerfile.dev
  frontend/a
  frontend/package-lock.json
  frontend/package.json
Labels: documentation, enhancement

#17 🔨 chore : 클러스터 docker 버전 이슈에 따른 docker-compose.dev.yml 수정
  docker-compose.dev.yml
Labels: enhancement

#18 🔨 github issue & pull request template 생성
  .github/ISSUE_TEMPLATE/bug_report_backend.yml
  .github/ISSUE_TEMPLATE/bug_report_frontend.yml
  .github/ISSUE_TEMPLATE/feature_request_backend.yml
  .github/ISSUE_TEMPLATE/feature_request_frontend.yml
  .github/ISSUE_TEMPLATE/refactoring_backend.yml
  .github/ISSUE_TEMPLATE/refactoring_frontend.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#20 🔨 DB 원격 접속을 위한 환경 구축
  .env.sample
  backend/.env.sample
  backend/Dockerfile.dev
  database/.devcontainer/devcontainer.json
  database/.env.sample
  database/Dockerfile.dev
  database/docker-entrypoint.dev.sh
  database/pg_hba.conf
  database/postgresql.conf
  docker-compose.dev.yml
  frontend/Dockerfile.dev
Labels: bug, enhancement, backend

#22 🔨 chore : GUI 로 PostgreSQL DB 관리하기
  .env.sample
  database/Dockerfile.dev
  docker-compose.dev.yml
Labels: enhancement, backend

#25 🔨 chore : .env 통합 및 docker compose 파일 수정
  .env.sample
  backend/.env.sample
  database/.env.sample
  docker-compose.dev.yml
  env_check.sh
  frontend/.env.sample
Labels: enhancement

#26 :hammer: chore : DB 테이블 생성 스크립트 실행 자동화
  database/configs/pg_hba.conf
  database/configs/postgresql.conf
  database/docker-entrypoint.dev.sh
  database/sql/init_db.sql
  docker-compose.dev.yml
Labels: enhancement, backend
